source "https://rubygems.org"

ruby "2.5.3"

gem "bourbon"
gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-inline_svg"
gem "middleman-autoprefixer"
gem "middleman-minify-html"
gem "middleman-livereload", "~> 3.4.3"
gem "neat"
gem "redcarpet"
gem "sassc"
